name: Qemu

on:
  push:
    branches: [ add_M1_test ]
  pull_request:
    branches: [ add_M1_test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install -y ninja-build
    - name: Build
      run: |
        set -ex
        mkdir build
        mkdir release
        export RELEASE_FOLDER=$PWD/release
        cd build
        ../configure --prefix=$RELEASE_FOLDER
        make
        make install
