name: Qemu

on:
  push:
    tags: [ 'Apple_M1_*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install -y ninja-build
    - name: Build
      run: |
        set -ex
        mkdir build
        mkdir release
        export RELEASE_FOLDER=$PWD/release
        cd build
        ../configure --prefix=$RELEASE_FOLDER --target-list=aarch64-softmmu
        make
        make install
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: qemu build
        path: |
          release
